1:  'Abbitte'
2:  'Antrag'
3:  'Anzug'
4:  'Bericht'
5:  'Budgetpostulat'
6:  'Initiative'
7:  'Interpellation'
8:  'Kleine Anfrage'
9:  'Motion'
10: 'Petition'
11: 'Planungsanzug'
12: 'Planungsauftrag'
13: 'Ratschlag'
14: 'Rekurs'
15: 'Resolution'
16: 'Rücktritt'
17: 'Schreiben'
18: 'Schriftliche Anfrage'
19: 'Vorgezogenes Budgetpostulat'
20: 'Wahl'
21: 'parl. Vorstoss'
