on:
  push:
    branches: 
    - docs
  workflow_dispatch:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
